sudo: false
language: ruby
rvm:
  - "2.4"
  - "2.5"
  - "2.6"
deploy:
  provider: rubygems
  api_key:
    secure: Z/EJy7D07xm84EpEE0EbjHP4MvZqeRISfMhdwFOrdX+3q4wW0EDiSXGIBUV37tzlt2Yv2eyV7UyQbgILXOO3LsgpKA83Fdu8xrk5gjfacAANfAsce1ixn6leg1GxLIvIhUov8Uh3yZDu8kFqscHO4aW0Pq7lF8ulXUICV3fHmWEABnFrJwPMVqpQs0BYViB8T+R6u14DjB7Yahaz8+r3w6oOQQQFRld5YiMb3dovNnDdXJtDPZO/mTpGKvdyCfelwlNTf3AkTo5XWVocXIeEeH0/SC0aW+6g9Q7p5KLHExFE1j05IW7sRfu5oQwl27qmwoxpVXca9DltKZrFAeevjl2L2Cd74p1Bv8tC0OEwO3LcdaDalFSPGT5sRtO8LstjmgNU50H4DZhbgB6sewgNslnAO5OJ8VhgQzl861gYP/5PrVOzWbVNXX/3jpGvTggFKcU/x4fkbj44xK0k7y7QY/YCL8P87xlzJjTvPP1zIWPC0Bg+/pVUTuyIyPf9LBALqJtYMHVPSqqGjc0fwKnMbijb8QYqoArCI0KX+KWRLXmWs8Abg7hz9t6J17lmW2fM/s36eohDgwkR/Stfw7RIygDzZUpuDYc8kD0iiErQ2fceb7G5ty3fr0Dg1FL2XX3ESo/PhgZY/m92Gh5nFwFBNmrY2Y+H6jL3qxLB50l5hEI=
  gem: github_merge_sign
  on:
    tags: true
    # pin to a ruby version to prevent multiple publish attempts.
    ruby: "2.6"
